import turtle 
t = turtle.Pen()
turtle.bgcolor("black")
t.pencolor("white")
t.width(5)
Gato = True
t.speed(5)
t.penup()
t.left(180)
t.forward(100)
t.right(90)
t.forward(300)
t.pendown()
t.right(180)
t.forward(600)
t.penup()
t.left(90)
t.forward(200)
t.pendown()
t.left(90)
t.forward(600)
t.penup()
t.right(90)
t.forward(200)
t.right(90)
t.forward(200)
t.pendown()
t.right(90)
t.forward(600)
t.penup()
t.left(90)
t.forward(200)
t.pendown()
t.left(90)
t.forward(600)

while(Gato):
    respuesta = input("elige una figura en el gato,!muy importante antes de comenzar x tira primero y despues¡, elige x o y: ")
    if (respuesta == "x" or respuesta == "y"):
        
        if respuesta == "x" :
            print("haz seleccionado x")
            respuesta = input("elige un numero del 1 al 9 en el gato: ")
            if (respuesta == "1" or respuesta == "2" or respuesta == "3" or respuesta == "4" or respuesta == "5" or respuesta == "6" or respuesta == "7" or respuesta == "8" or respuesta == "9"):
                if respuesta == "1":
                        t.penup()
                        t.goto(-200,200)
                        t.pendown()
                        t.left(60)
                        t.forward(50)
                        t.left(180)
                        t.forward(100)
                        t.penup()
                        t.left(120)
                        t.forward(50)
                        t.pendown()
                        t.left(120)
                        t.forward(100)
                elif respuesta == "2":
                        t.penup()
                        t.goto(0,200)
                        t.pendown()
                        t.left(60)
                        t.forward(50)
                        t.left(180)
                        t.forward(100)
                        t.penup()
                        t.left(120)
                        t.forward(50)
                        t.pendown()
                        t.left(120)
                        t.forward(100)
                elif respuesta == "3":
                        t.penup()
                        t.goto(200,200)
                        t.pendown()
                        t.left(60)
                        t.forward(50)
                        t.left(180)
                        t.forward(100)
                        t.penup()
                        t.left(120)
                        t.forward(50)
                        t.pendown()
                        t.left(120)
                        t.forward(100)
                elif respuesta == "4":
                        t.penup()
                        t.goto(-200,0)
                        t.pendown()
                        t.left(60)
                        t.forward(50)
                        t.left(180)
                        t.forward(100)
                        t.penup()
                        t.left(120)
                        t.forward(50)
                        t.pendown()
                        t.left(120)
                        t.forward(100)
                elif respuesta == "5":
                        t.penup()
                        t.goto(0,0)
                        t.pendown()
                        t.left(60)
                        t.forward(50)
                        t.left(180)
                        t.forward(100)
                        t.penup()
                        t.left(120)
                        t.forward(50)
                        t.pendown()
                        t.left(120)
                        t.forward(100)
                elif respuesta == "6":
                        t.penup()
                        t.goto(200,0)
                        t.pendown()
                        t.left(60)
                        t.forward(50)
                        t.left(180)
                        t.forward(100)
                        t.penup()
                        t.left(120)
                        t.forward(50)
                        t.pendown()
                        t.left(120)
                        t.forward(100)
                elif respuesta == "7":
                        t.penup()
                        t.goto(-200,-200)
                        t.pendown()
                        t.left(60)
                        t.forward(50)
                        t.left(180)
                        t.forward(100)
                        t.penup()
                        t.left(120)
                        t.forward(50)
                        t.pendown()
                        t.left(120)
                        t.forward(100)
                elif respuesta == "8":
                        t.penup()
                        t.goto(0,-200)
                        t.pendown()
                        t.left(60)
                        t.forward(50)
                        t.left(180)
                        t.forward(100)
                        t.penup()
                        t.left(120)
                        t.forward(50)
                        t.pendown()
                        t.left(120)
                        t.forward(100)
                elif respuesta == "9":
                        t.penup()
                        t.goto(200,-200)
                        t.pendown()
                        t.left(60)
                        t.forward(50)
                        t.left(180)
                        t.forward(100)
                        t.penup()
                        t.left(120)
                        t.forward(50)
                        t.pendown()
                        t.left(120)
                        t.forward(100)
                
        if (respuesta == "1" or respuesta == "2" or respuesta == "3" or respuesta == "4" or respuesta == "5" or respuesta == "6" or respuesta == "7" or respuesta == "8" or respuesta == "9"):
                print ("es turno del jugador 2")
                Gato = False
                
        if respuesta == "y":
            print("haz seleccionado △")
            respuesta = input("elige un numero del 1 al 9 en el gato: ")
            if (respuesta == "1" or respuesta == "2" or respuesta == "3" or respuesta == "4" or respuesta == "5" or respuesta == "6" or respuesta == "7" or respuesta == "8" or respuesta == "9"):
                if respuesta == "1":
                        t.penup()
                        t.goto(-200,200)
                        t.right(90)
                        t.forward(25)
                        t.pendown()
                        t.left(90)
                        t.forward(50)
                        t.left(120)
                        t.forward(100)
                        t.left(120)
                        t.forward(100)
                        t.left(120)
                        t.forward(50)               
                if respuesta == "2":
                        t.penup()
                        t.goto(0,200)
                        t.right(90)
                        t.forward(25)
                        t.pendown()
                        t.left(90)
                        t.forward(50)
                        t.left(120)
                        t.forward(100)
                        t.left(120)
                        t.forward(100)
                        t.left(120)
                        t.forward(50)          
                if respuesta == "3":
                        t.penup()
                        t.goto(200,200)
                        t.right(90)
                        t.forward(25)
                        t.pendown()
                        t.left(90)
                        t.forward(50)
                        t.left(120)
                        t.forward(100)
                        t.left(120)
                        t.forward(100)
                        t.left(120)
                        t.forward(50)     
                if respuesta == "4":
                        t.penup()
                        t.goto(-200,0)
                        t.right(90)
                        t.forward(25)
                        t.pendown()
                        t.left(90)
                        t.forward(50)
                        t.left(120)
                        t.forward(100)
                        t.left(120)
                        t.forward(100)
                        t.left(120)
                        t.forward(50)   
                if respuesta == "5":
                        t.penup()
                        t.goto(0,0)
                        t.right(90)
                        t.forward(25)
                        t.pendown()
                        t.left(90)
                        t.forward(50)
                        t.left(120)
                        t.forward(100)
                        t.left(120)
                        t.forward(100)
                        t.left(120)
                        t.forward(50)    
                if respuesta == "6":
                        t.penup()
                        t.goto(200,0)
                        t.right(90)
                        t.forward(25)
                        t.pendown()
                        t.left(90)
                        t.forward(50)
                        t.left(120)
                        t.forward(100)
                        t.left(120)
                        t.forward(100)
                        t.left(120)
                        t.forward(50)              
                if respuesta == "7":
                        t.penup()
                        t.goto(-200,-200)
                        t.right(90)
                        t.forward(25)
                        t.pendown()
                        t.left(90)
                        t.forward(50)
                        t.left(120)
                        t.forward(100)
                        t.left(120)
                        t.forward(100)
                        t.left(120)
                        t.forward(50)              
                if respuesta == "8":
                        t.penup()
                        t.goto(0,-200)
                        t.right(90)
                        t.forward(25)
                        t.pendown()
                        t.left(90)
                        t.forward(50)
                        t.left(120)
                        t.forward(100)
                        t.left(120)
                        t.forward(100)
                        t.left(120)
                        t.forward(50)    
                if respuesta == "9":
                        t.penup()
                        t.goto(200,-200)
                        t.right(90)
                        t.forward(25)
                        t.pendown()
                        t.left(90)
                        t.forward(50)
                        t.left(120)
                        t.forward(100)
                        t.left(120)
                        t.forward(100)
                        t.left(120)
                        t.forward(50)       
    else:
        print("no es una respuesta valida")
turtle.exitonclick()